### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/collection/IterableOnce

### ISSUE THREAD

**Issue by jeremyross** [jam01/xtrasonnet#10]
Using 0.4.2 in Camel, getting:

> java.lang.NoClassDefFoundError: scala/collection/IterableOnce

**Comment by jam01** [comment]
Hey @jeremyross just saw this. Can you include more info about your route? We've been using xtrasonnet with Camel for a little while now without issues.

**Comment by jam01** [comment]
at first glance seems a Scala dependency mismatch

**Comment by jeremyross** [comment]
Yeah possibly. Here's the dep tree
```
[INFO] +- io.github.jam01:camel-xtrasonnet:jar:0.4.2:compile
[INFO] |  +- io.github.jam01:xtrasonnet:jar:0.4.2:compile
[INFO] |  |  +- io.github.jam01:sjsonnet_2.13:jar:0.4.3-02:compile
[INFO] |  |  |  +- com.lihaoyi:fastparse_2.13:jar:2.3.1:compile
[INFO] |  |  |  |  +- com.lihaoyi:sourcecode_2.13:jar:0.2.3:compile
[INFO] |  |  |  |  \- com.lihaoyi:geny_2.13:jar:0.6.5:compile
[INFO] |  |  |  +- com.lihaoyi:pprint_2.13:jar:0.6.1:compile
[INFO] |  |  |  |  \- com.lihaoyi:fansi_2.13:jar:0.2.10:compile
[INFO] |  |  |  +- com.lihaoyi:ujson_2.13:jar:1.3.7:compile
[INFO] |  |  |  |  \- com.lihaoyi:upickle-core_2.13:jar:1.3.7:compile
[INFO] |  |  |  +- com.lihaoyi:scalatags_2.13:jar:0.9.3:compile
[INFO] |  |  |  +- org.scala-lang.modules:scala-collection-compat_2.13:jar:2.4.0:compile
[INFO] |  |  |  |  \- org.scala-lang:scala-library:jar:2.11.12:compile
```
Adding this seemed to fix it:
```
<dependency>
    <groupId>org.scala-lang</groupId>
    <artifactId>scala-library</artifactId>
    <version>2.13.9</version>
</dependency>
```

**Comment by jam01** [comment]
It makes sense that adding scala 2.13.9 overrides the transitive dep, but I'm still unsure why I haven't seen this before. 

I'm planning to rebase sjsonnet to the latest 2.13 scala though, because of some vulnerabilities though. The upgrade should solve this issue either way.

**Comment by jam01** [comment]
@jeremyross v0.5.1 should solve this for you.

What version of camel are you using?

**Comment by jeremyross** [comment]
this project is using 3.20.1

**Comment by jam01** [comment]
@jeremyross are we good to close this?

**Comment by jam01** [comment]
I just ran into this issue. For me it was caused by using

`org.apache.camel.springboot:camel-spring-boot-dependencies`

instead of 

`org.apache.camel.springboot:camel-spring-boot-bom`

in `dependencyManagement`. 

`-bom` is the what's in the spring-boot archetype starting in [3.17](https://github.com/apache/camel-spring-boot/blob/camel-spring-boot-3.17.0/archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/pom.xml#L50) whereas `-dependencies` was last used in [3.16](https://github.com/apache/camel-spring-boot/blob/camel-spring-boot-3.16.0/archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/pom.xml#L50).

Ultimately, the issue is definitely due to some dependency overriding the scala-library version that xtrasonnet depends on. Gonna close this now, let me know if you disagree.
